config/routes.rb
Betastore::Application.routes.draw do
  namespace :admin do
    resources :products
    resources :orders
    root :to => 'dashboard#index'
  end

  get '/categories/:category_id/products' => 'products#index', as: 'category_products'

  get '/cart' => 'cart_items#index', as: 'cart_items'
  post '/products/:product_id/cart_items' => 'cart_items#create', as: 'add_to_cart'

  resources :subscriptions

  get '/sign_up' => 'customers#new', as: 'sign_up'
  post '/sign_up' => 'customers#create'

  resources :products
  root :to => 'products#index'

  get '/log_in'  => 'log_ins#new', as: 'log_in'
  post '/log_in'  => 'log_ins#create'
  post '/log_out' => 'log_ins#destroy', as: 'log_out'

  get '/forgot_password' => 'password_resets#new', as: 'forgot_password'
  post '/forgot_password' => 'password_resets#create'
  get '/reset_password/:id/:token' => 'password_resets#edit', as: 'reset_password'
  post '/reset_password/:id/:token' => 'password_resets#update'

  get '/checkout' => 'orders#new', as: 'checkout'
  post '/checkout' => 'orders#create'

  

  

end

app/controllers/log_ins_controller.rb
class LogInsController < ApplicationController
	skip_before_filter :require_log_in

  	def create
    	customer = Customer.find_by(email: params[:email])
	    if customer && customer.authenticate(params[:password]) 
    	  	cookies.signed[:customer_id] = customer.id
      		redirect_to products_path
    	else
      		redirect_to log_in_path, alert: 'Log In Failed'
      end
  	end
  	def destroy
    	cookies.delete(:customer_id)
    	redirect_to products_path
  	end
end

app/views/log_ins/new.html.erb
<h1>Log In</h1>

<% if flash[:alert] %>
  <p style="color: red"><%= flash[:alert] %></p>
<% end %>

<%= form_tag do %>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  
  <div>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  
  <%= button_tag "Log In" %>
<% end %>

<p>
	Don't have an account? 
	<%= link_to "Sign Up", sign_up_path %>
</p>

<p>
  Forgot your password?
  <%= link_to "Forgot Password", forgot_password_path %>
  </p>