config/routes.rb
Betastore::Application.routes.draw do
  namespace :admin do
    resources :products
    resources :orders
    root :to => 'dashboard#index'
  end

  get '/categories/:category_id/products' => 'products#index', as: 'category_products'

  get '/cart' => 'cart_items#index', as: 'cart_items'
  post '/products/:product_id/cart_items' => 'cart_items#create', as: 'add_to_cart'

  resources :subscriptions

  get '/sign_up' => 'customers#new', as: 'sign_up'
  post '/sign_up' => 'customers#create'

  resources :products
  root :to => 'products#index'

  get '/log_in'  => 'log_ins#new', as: 'log_in'
  post '/log_in'  => 'log_ins#create'
  post '/log_out' => 'log_ins#destroy', as: 'log_out'

  get '/forgot_password' => 'password_resets#new', as: 'forgot_password'
  post '/forgot_password' => 'password_resets#create'
  get '/reset_password/:id/:token' => 'password_resets#edit', as: 'reset_password'
  post '/reset_password/:id/:token' => 'password_resets#update'

  get '/checkout' => 'orders#new', as: 'checkout'
  post '/checkout' => 'orders#create'

  

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items
  has_many :product_categorizations
  has_many :categories, :through => :product_categorizations

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  # def image_url
  #   "/products/#{name.downcase.tr(' ', '_')}.jpg"
  # end

  def self.in_category(category_id)
    includes(:product_categorizations)
      .where('product_categorizations.category_id' => category_id)
  end

  def self.search(term)
    # where("name ILIKE ?", "%#{term}%")
    where("name ILIKE ?", term)
  end

end

app/models/products.rb
class Products < ActiveRecord::Base
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @products = Product.all
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

   # POST /admin/products
  # POST /admin/products.json
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
      if @product.update_attributes(product_params)
        redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy
      redirect_to admin_products_url, notice: 'Product was deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
       params.require(:product).permit(:name, :price) 
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	# skip_before_filter :require_log_in


	def index
	    @categories = Category.all

	    scope = Product

	    if params[:min_price].present?
	      scope = scope.where('price >= ?', params[:min_price])
	    end

	    if params[:max_price].present?
	      scope = scope.where('price <= ?', params[:min_price])
	    end

	    if params[:category_id].present?
	      scope = scope.in_category(params[:category_id])
	    end

	    if params[:search].present?
	    	scope = scope.search
	    end
	    @products = scope.page(params[:page] || 1).per(10)

		respond_to do |format| 
			format.html 
			format.rss
			format.json do
				render json: @products
			end
		end
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			render json: @product
		else
			render json: {errors: @product.errors }, status: 422
		end
	end


	def show
		@product = Product.find(params[:id])
	end


	private
	def product_params
		params.require(:product).permit(:name, :price)
	end
# do delete
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product], html: { role: 'form' }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', style: 'width: 200px' %>

  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control', style: 'width: 200px' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Products', admin_products_path %></li>
  <li><%= link_to @product.name, admin_product_path(@product)%></li>
  <li class="active">Edit</li>
</ol>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Listing admin_products</h1>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= number_to_currency product.price %></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Products', admin_products_path %></li>
  <li class="active">New Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<ol class="breadcrumb">
  <li><%= link_to 'Products', admin_products_path %></li>
  <li class="active"><%= @product.name %></li>
</ol>


<p><strong>Price:</strong> <%= number_to_currency @product.price %></p>

<%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-default' %>
<%= link_to 'Destroy', admin_product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>